### ISSUE TITLE
You don't have write permissions on ubuntu-latest workflow

### ISSUE THREAD

**Issue by viktorianer** [tomferreira/action-bundler-audit#2]
When using this action, it will fail with the following error:

```bash
Run tomferreira/action-bundler-audit@v1
Run reviewdog/action-setup@v1
Run $GITHUB_ACTION_PATH/install.sh
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Run echo "::group::📖 reviewdog -h"
📖 reviewdog -h
Run $GITHUB_ACTION_PATH/script.sh
 Installing bundler-audit with extensions ... https://github.com/rubysec/bundler-audit
  ERROR:  While executing gem ... (Gem::FilePermissionError)
      You don't have write permissions for the /var/lib/gems/3.0.0 directory.
  Error: Process completed with exit code 1.
```

Looks like this line https://github.com/tomferreira/action-bundler-audit/blob/main/script.sh#L33 is can not be done.

The only thing I can see in comparison to RuboCop action, is this different line https://github.com/reviewdog/action-rubocop/blob/master/script.sh#L8?!

My setup for this action (shortened to important lines):

```yml
...
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

...
    steps:
...
      - name: Bundler Audit with reviewdog
        uses: tomferreira/action-bundler-audit@v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          tool_name: Bundler Audit
...
```
